import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api, money, shortDate } from '../api.js';
import { useAuth } from '../context/AuthContext.jsx';
import { Badge, Empty, PageHeader, Spinner, StatCard } from '../components/UI.jsx';

export default function Dashboard() {
  const { user } = useAuth(); const [data,setData]=useState(null); const [error,setError]=useState('');
  useEffect(()=>{api('/dashboard').then(setData).catch(e=>setError(e.message));},[]);
  if(!data) return <div>{error?<div className="alert error">{error}</div>:<Spinner/>}</div>;
  if(user.role==='tenant') return <TenantDashboard data={data} user={user}/>;
  const s=data.stats;
  return <><PageHeader eyebrow="Portfolio overview" title={`Good evening, ${user.name.split(' ')[0]}`} description="Here’s the current health of your rental portfolio." action={<Link className="btn primary" to="/rent">View rent ledger</Link>}/><div className="stats-grid"><StatCard label="Collected this month" value={money(s.collectedThisMonth)} sub={`${money(s.outstandingBalance)} outstanding`} icon="dollar"/><StatCard label="Occupancy" value={`${s.occupancyRate}%`} sub={`${s.occupied} of ${s.units} units occupied`} icon="home"/><StatCard label="Net cash this month" value={money(s.netCashThisMonth)} sub={`${money(s.expensesThisMonth)} expenses`} icon="chart"/><StatCard label="Open maintenance" value={s.openMaintenance} sub={`${s.activeLeases} active leases`} icon="wrench"/></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Needs attention</span><h2>Outstanding charges</h2></div><Link to="/rent">View all</Link></div>{data.overdue?.length?<div className="list">{data.overdue.map(c=><div className="list-row" key={c._id}><div><strong>{c.description}</strong><span>Due {shortDate(c.dueDate)}</span></div><div className="list-right"><strong>{money(c.balance)}</strong><Badge tone="danger">Overdue</Badge></div></div>)}</div>:<Empty title="All caught up" text="There are no overdue charges right now."/>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Operations</span><h2>Maintenance queue</h2></div><Link to="/maintenance">Manage</Link></div>{data.maintenance?.length?<div className="list">{data.maintenance.map(m=><div className="list-row" key={m._id}><div><strong>{m.title}</strong><span>{m.propertyId?.name} · {m.unitId?.label}</span></div><div className="list-right"><Badge tone={m.priority==='emergency'?'danger':m.priority==='high'?'warning':'neutral'}>{m.priority}</Badge><span className="status-text">{m.status.replaceAll('_',' ')}</span></div></div>)}</div>:<Empty title="No open requests" text="Maintenance requests will appear here."/>}</section></div></>;
}

function TenantDashboard({data,user}){return <><PageHeader eyebrow="Tenant portal" title={`Welcome, ${user.name.split(' ')[0]}`} description="View your rent balance, lease, payments, and maintenance requests." action={<Link className="btn primary" to="/rent">Pay rent</Link>}/><div className="tenant-hero"><div><span>Current balance</span><strong>{money(data.balance)}</strong><p>{data.openCharges?.[0]?`Next due: ${shortDate(data.openCharges[0].dueDate)}`:'No open charges'}</p></div><div className="tenant-property"><span>Your home</span><strong>{data.lease?.propertyId?.name||'No active lease'}</strong><p>{data.lease?.propertyId?`${data.lease.propertyId.address1}, ${data.lease.propertyId.city}`:'Contact your property manager.'}</p></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Rent</span><h2>Open charges</h2></div><Link to="/rent">Details</Link></div>{data.openCharges?.length?<div className="list">{data.openCharges.map(c=><div className="list-row" key={c._id}><div><strong>{c.description}</strong><span>{shortDate(c.dueDate)}</span></div><strong>{money(c.balance)}</strong></div>)}</div>:<Empty title="No balance due" text="Your account has no open charges."/>}</section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Maintenance</span><h2>Open requests</h2></div><Link to="/maintenance">New request</Link></div>{data.maintenance?.length?<div className="list">{data.maintenance.map(m=><div className="list-row" key={m._id}><div><strong>{m.title}</strong><span>{shortDate(m.createdAt)}</span></div><Badge tone="neutral">{m.status.replaceAll('_',' ')}</Badge></div>)}</div>:<Empty title="Nothing open" text="Submit a request anytime from the maintenance page."/>}</section></div></>}
